#!/bin/bash
### BEGIN INIT INFO
# Provides: rigpingctl
# Required-Start:    $all
# Required-Stop: 
# Default-Start:     5 
# Default-Stop:      6 
# Short-Description: Rig controller controls and monitorize rig
### END INIT INFO

source /etc/rpi-rele.conf

RETVAL=0

PIDFILE_CHAN1=/var/run/rigping1.pid
PIDFILE_CHAN2=/var/run/rigping2.pid
PIDFILE_CHAN3=/var/run/rigping3.pid
PIDFILE_CHAN4=/var/run/rigping4.pid

start()
{
    echo "Starting rigpingctl service..."
    if [[ $CHAN1_GPIO ]]; then
        start-stop-daemon --start -b --make-pidfile --pidfile $PIDFILE_CHAN1 --exec /usr/bin/rig-ping-chan1.sh
    fi

    if [[ $CHAN2_GPIO ]]; then
        start-stop-daemon --start -b --make-pidfile --pidfile $PIDFILE_CHAN2 --exec /usr/bin/rig-ping-chan2.sh
    fi

    if [[ $CHAN3_GPIO ]]; then
        start-stop-daemon --start -b --make-pidfile --pidfile $PIDFILE_CHAN3 --exec /usr/bin/rig-ping-chan3.sh
    fi

    if [[ $CHAN4_GPIO ]]; then
        start-stop-daemon --start -b --make-pidfile --pidfile $PIDFILE_CHAN4 --exec /usr/bin/rig-ping-chan4.sh
    fi
    echo "Started"
}

stop()
{
    echo "Stopping rigpingctl service..."
    if [[ $CHAN1_GPIO ]]; then
        start-stop-daemon --stop --quiet --oknodo --pidfile $PIDFILE_CHAN1
    fi

    if [[ $CHAN2_GPIO ]]; then
        start-stop-daemon --stop --quiet --oknodo --pidfile $PIDFILE_CHAN2
    fi

    if [[ $CHAN3_GPIO ]]; then
        start-stop-daemon --stop --quiet --oknodo --pidfile $PIDFILE_CHAN3
    fi

    if [[ $CHAN4_GPIO ]]; then
        start-stop-daemon --stop --quiet --oknodo --pidfile $PIDFILE_CHAN4
    fi
    echo "Stopped"
}

case "$1" in
start)
    start
    ;;
stop)
    stop
    ;;
restart)
    stop
    sleep 1
    start
    ;;
*)
    echo $"Usage: $prog {start|stop|restart}"
    exit 1
esac

exit $RETVAL

