#!/bin/bash
### BEGIN INIT INFO
# Provides: rigctl
# Required-Start:    $all
# Required-Stop: 
# Default-Start:     5 
# Default-Stop:      6 
# Short-Description: Rig controller controls and monitorize rig
### END INIT INFO

source /etc/rpi-rele.conf

RETVAL=0

start()
{
    echo "Starting rigctl service..."
    if [[ $GPIO_PWR1 ]]; then
        nohup rig-monit-chan1.sh > /dev/null 2>&1 < /dev/null &
    fi

    if [ $GPIO_PWR2 ]; then
        nohup rig-monit-chan2.sh > /dev/null 2>&1 < /dev/null &
    fi

    if [ $GPIO_PWR3 ]; then
        nohup rig-monit-chan3.sh > /dev/null 2>&1 < /dev/null &
    fi

    if [ $GPIO_PWR4 ]; then
        nohup rig-monit-chan4.sh > /dev/null 2>&1 < /dev/null &
    fi
    echo "Started"
}

stop()
{
    echo "Stopping rigctl service..."
    if [[ $GPIO_RST1 ]]; then
        killall rig-monit-chan1.sh
    fi

    if [[ $GPIO_RST1 ]]; then
        killall rig-monit-chan2.sh
    fi

    if [[ $GPIO_RST1 ]]; then
        killall rig-monit-chan3.sh
    fi

    if [[ $GPIO_RST1 ]]; then
        killall rig-monit-chan4.sh
    fi
    echo "Stopped"
}

case "$1" in
start)
    start
    ;;
stop)
    stop
    ;;
restart)
    stop
    start
    ;;
*)
    echo $"Usage: $prog {start|stop|restart}"
    exit 1
esac

exit $RETVAL

