#!/bin/bash
### BEGIN INIT INFO
# Provides: rigctl
# Required-Start:    $all
# Required-Stop: 
# Default-Start:     5 
# Default-Stop:      6 
# Short-Description: Rig controller controls and monitorize rig
### END INIT INFO

RETVAL=0

start()
{
    echo "Starting rigctl service..."
    nohup rig-monit.sh > /dev/null 2>&1 < /dev/null &
    echo "Started"
}

stop()
{
    echo "Stopping rigctl service..."
    killall rig-monit.sh
    echo "Stopped"
}

case "$1" in
start)
    start
    ;;
stop)
    stop
    ;;
restart)
    stop
    start
    ;;
*)
    echo $"Usage: $prog {start|stop|restart}"
    exit 1
esac

exit $RETVAL

