#!/bin/bash
### BEGIN INIT INFO
# Provides: rigctl
# Required-Start:    $all
# Required-Stop: 
# Default-Start:     5 
# Default-Stop:      6 
# Short-Description: Rig controller controls and monitorize rig
### END INIT INFO

source /etc/rpi-rele.conf

RETVAL=0

PIDFILE_CHAN1=/var/run/chan1.pid
PIDFILE_CHAN2=/var/run/chan2.pid
PIDFILE_CHAN3=/var/run/chan3.pid
PIDFILE_CHAN4=/var/run/chan4.pid

start()
{
    log_daemon_msg "Starting rigctl service..."
    if [[ $GPIO_PWR1 ]]; then
	start-stop-daemon --start -b --pidfile $PIDFILE_CHAN1 --exec  /usr/bin/rig-monit-chan1.sh
    fi

    if [ $GPIO_PWR2 ]; then
	start-stop-daemon --start -b --pidfile $PIDFILE_CHAN2 --exec  /usr/bin/rig-monit-chan2.sh
    fi

    if [ $GPIO_PWR3 ]; then
	start-stop-daemon --start -b --pidfile $PIDFILE_CHAN3 --exec  /usr/bin/rig-monit-chan3.sh
    fi

    if [ $GPIO_PWR4 ]; then
	start-stop-daemon --start -b --pidfile $PIDFILE_CHAN4 --exec  /usr/bin/rig-monit-chan4.sh
    fi
    log_daemon_msg "Started"
}

stop()
{
    echo "Stopping rigctl service..."
    if [[ $GPIO_RST1 ]]; then
        start-stop-daemon --stop --quiet --oknodo --pidfile $PIDFILE_CHAN1
    fi

    if [[ $GPIO_RST2 ]]; then
        start-stop-daemon --stop --quiet --oknodo --pidfile $PIDFILE_CHAN2
    fi

    if [[ $GPIO_RST3 ]]; then
        start-stop-daemon --stop --quiet --oknodo --pidfile $PIDFILE_CHAN3
    fi

    if [[ $GPIO_RST4 ]]; then
        start-stop-daemon --stop --quiet --oknodo --pidfile $PIDFILE_CHAN4
    fi
    echo "Stopped"
}

case "$1" in
start)
    start
    ;;
stop)
    stop
    ;;
restart)
    stop
    start
    ;;
*)
    echo $"Usage: $prog {start|stop|restart}"
    exit 1
esac

exit $RETVAL

